version: "3"
services:
  graphite-statsd:
    container_name: graphite-statsd
    image: hopsoft/graphite-statsd
    ports:
      - "192.168.10.46:80:80"
      - "192.168.10.46:2003-2004:2003-2004"
      - "192.168.10.46:2023-2024:2023-2024"
      - "192.168.10.46:8125:8125/udp"
      - "192.168.10.46:8126:8126"
    volumes:
      - "./data/graphite/storage:/opt/graphite/storage"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
